spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/milan_telecom
    username: bl4z
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  kafka:
    bootstrap-servers: localhost:9092

traffic:
  kafka:
    topic: milan.traffic.raw
